### PR TITLE
Android: import new Android overlay in more places

### PR DESCRIPTION
**Pull request by finagolfin**
Also, fix one test and add the right path for `touch` in the plugin tests.

@dschaefer2, I use this patch to build both natively on Android and [cross-compile for my Android CI](https://github.com/finagolfin/swift-android-sdk/blob/cb93bf31adeefba44ce8041a90f6c88f7241ae2d/swift-android-ci.patch#L114). It would be good to get it in before the upcoming 6.1 branch: should be easy to review as it touches nothing outside Android and makes simple changes for Android.

### CODE REVIEW

**Comment by finagolfin** [comment]
Ping @bnbarham, a CI run and we can get this in.

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
I believe self-hosted has been having issues, but let's see 😬

**Comment by finagolfin** [comment]
Self-hosted linux passed, but self-hosted mac CI appears to be broken for the last week, maybe because of some change in the macOS CI environment for self-hosted.

**Comment by dschaefer2** [comment]
Yup, known issue with the macOS self hosted CI job. I'm waiting patiently for a fix. It's affecting all PRs at the moment.

**Comment by finagolfin** [comment]
It looks like Mishal was working on it, re-ran this one a couple times, but it was always broken.

**Comment by dschaefer2** [comment]
Yup, he assures me he's still working on it.

**Comment by finagolfin** [comment]
@MaxDesiatov, would you merge?

**Comment by finagolfin** [comment]
Ping @bnbarham, finally passed CI, ready for merge.

**Comment by dschaefer2** [comment]
Thanks!

**Comment by dschaefer2** [comment]
BTW, I'm in Ottawa Canada time.

**Comment by finagolfin** [comment]
> BTW, I'm in Ottawa Canada time.

I know, I saw it on your github profile, which is why I didn't ask you 7 hours ago when I asked Max in London instead. 😄

**Pull request merged**
