### PR TITLE
Remove `temp_await` from Snippets

### PR DESCRIPTION
**Pull request by AndrewHoos**
Remove temp_await from Snippets

### Motivation:

temp_await is unsafe and it would be better to use true async methods

### Modifications:

Remove usages of temp_await from Snippets

### Result:

Safer more modern Swift code

### CODE REVIEW

**Comment by AndrewHoos** [comment]
@swift-ci test

**Review by MaxDesiatov — APPROVED** [review]
Thanks!

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Pull request merged**
