### PR TITLE
Remove some PIF overrides to match Xcode behavior

### PR DESCRIPTION
**Pull request by jakepetroules**
Helps to simplify compatibility testing.

### CODE REVIEW

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Review by owenv — APPROVED** [review]

**Comment by jakepetroules** [comment]
@swift-ci please smoke test macOS

**Comment by jakepetroules** [comment]
@swift-ci please smoke test Linux

**Comment by jakepetroules** [comment]
@swift-ci please test Linux

**Comment by jakepetroules** [comment]
@swift-ci please test macOS

**Comment by jakepetroules** [comment]
@swift-ci please test failed

**Comment by jakepetroules** [comment]
@swift-ci please test macOS

**Pull request merged**
