### PR TITLE
Guard resource access header with  __OBJC__ to avoid including Foundation.h

### PR DESCRIPTION
**Pull request by rjmansfield**
Guard resource access header with __OBJC__ to avoid including Foundation.h in languages that do not support it. i.e. non-objc/c++

Add check the file extension for assembly files to not include Foundation.h there as well.

Fixes: #7949

### CODE REVIEW

**Comment by dschaefer2** [comment]
@swift-ci please test

**Comment by rjmansfield** [comment]
Window CI builders appears to be out of disk space. 

```
C:\Users\swift-ci\jenkins\workspace\swiftpm-PR-windows\swift\lib\Serialization\Serialization.cpp : fatal error C1085: Cannot write compiler generated file: 'T:\5\tools\swift\lib\Serialization\CMakeFiles\swiftSerialization.dir\Serialization.cpp.obj': No space left on device
ninja: build stopped: subcommand failed.
```

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Review by MaxDesiatov — COMMENTED** [review]
Would you mind adding a test that verifies the desired behavior?

**Comment by luispadron** [comment]
Has there been any progress on this? This blocks us from using some packages 🙏🏼

**Comment by rjmansfield** [comment]
Adding a .S or .cpp file in Simple/Sources/MixedClangResource will reproduce the reported issue of trying to -include resource_bundle_accessor.h for a file in assembly and C++ where the objc in the header is not accepted. Without the change, testResourcesInMixedClangPackage will fail; with the change, test passes. 

 Please let me know if there's additional testing you'd like to see added for this case.

**Comment by MaxDesiatov** [comment]
Great, now this PR needs a test case you've described added to test suite so that it's tested on CI.

**Comment by rjmansfield** [comment]
Does testResourcesInMixedClangPackage not run in CI?

**Comment by rjmansfield** [comment]
Looks at the jenkins logs it does:

`[1362/1838] Testing FunctionalTests.ResourcesTests/testResourcesInMixedClangPackage
`

I'll try again. The addition of the files with the .S and .cpp extension in my PR to the Fixtures/Resources/Simple/Sources/MixedClangResource directory means the ResourcesInMixedClangPackage test demonstrates the issue and verifies the fix.

Adding a separate test would mean replicating ResourcesInMixedClangPackage. That test was originally added for effectively the same issue, i.e. resource header would work with Mixed sources, but it only considered C, and not C++ or assembly.

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Review by MaxDesiatov — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by rjmansfield** [comment]
Can someone retrigger the tests, and merge if OK?

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by dschaefer2** [comment]
Yup. Thanks for the reminder :).

**Review by jmschonfeld — APPROVED** [review]

**Review by dschaefer2 — APPROVED** [review]

**Comment by dschaefer2** [comment]
Thanks Ryan!

**Comment by DordeDimitrijev** [comment]
@dschaefer2  when will these changes be released?

**Comment by aditi-s3** [comment]
@dschaefer2 @MaxDesiatov what is the timeline to get this fix released? 
This blocks building certain packages via command line in CI :pray:

**Comment by dschaefer2** [comment]
It will come in the 6.1 Swift toolchain release. Not sure when that is but we have started ramping down towards it.

**Pull request merged**
