### PR TITLE
Add new SwiftPM team members to CODEOWNERS.

### PR DESCRIPTION
**Pull request by dschaefer2**

### CODE REVIEW

**Comment by dschaefer2** [comment]
@swift-ci please test

**Comment by dschaefer2** [comment]
@swift-ci please test

**Review by MaxDesiatov — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Review by jakepetroules — APPROVED** [review]

**Review by bnbarham — APPROVED** [review]

**Comment by dschaefer2** [comment]
@swift-ci please test

**Comment by dschaefer2** [comment]
@swift-ci please test windows

**Pull request merged**
