### PR TITLE
NFC: Rename `PinsStore` to `PackageResolvedStore`

### PR DESCRIPTION
**Pull request by MaxDesiatov**
### Motivation:

Implemented `Package.resolved` feature is called "pins", which can be confusing for SwiftPM contributors.

### Modifications:

Renamed uses of `pins` in types and functions to use `ResolvedPackage`, `packageResolved`, or `resolution` instead, depending on the exact context of use.

### Result:

It is easier for contributors to find relevant code.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Review by xedin — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Pull request merged**
