### PR TITLE
Add basic tests for `completion-tool list-{dependencies,snippets}`

### PR DESCRIPTION
**Pull request by plemarquand**
There were not tests covering off these two completion-tool commands. This covers off the happy path for all the `list-*` commands. There are still not tests for the completion-tool `generate-*-script` commands

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by plemarquand** [comment]
@swift-ci test

**Review by bkhouri — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by bkhouri** [comment]
> There were not tests covering off these two completion-tool commands. This covers off the happy path for all the `list-*` commands. There are still not tests for the completion-tool `generate-*-script` commands

Does a GH issue exist to augment the test the cover the `generate-*-script` completion commands commands?  Can you share it here if so, or create one if it does not exist?

**Comment by plemarquand** [comment]
@bkhouri Does every change need a corresponding GitHub issue?

**Comment by plemarquand** [comment]
@swift-ci test windows

**Comment by bkhouri** [comment]
> @bkhouri Does every change need a corresponding GitHub issue?

Likely not, but it would be nice to track the missing work we know about so we don't loose track of it!

**Review by MaxDesiatov — APPROVED** [review]

**Pull request merged**
