### PR TITLE
Make access modifiers public for users of the package.

### PR DESCRIPTION
**Pull request by shawnhyam**
Change a few access modifiers to public.

### Motivation:

As a user of the package, I am trying to access these properties.

### CODE REVIEW

**Review by MaxDesiatov — APPROVED** [review]

**Comment by dschaefer2** [comment]
@swift-ci please test
@swift-ci please test windows

**Comment by dschaefer2** [comment]
@swift-ci please test

**Comment by dschaefer2** [comment]
@swift-ci please test

**Comment by plemarquand** [comment]
@swift-ci please test

**Review by jakepetroules — APPROVED** [review]

**Comment by dschaefer2** [comment]
@swift-ci please test linux

**Comment by dschaefer2** [comment]
@swift-ci please test windows

**Pull request merged**
