### PR TITLE
Ensure package plugin sandbox contents is deterministic

### PR DESCRIPTION
**Pull request by owenv**
Previously, nondeterministic item replacement directory paths could be included in the sandbox content. This can lead to spurious incremental rebuilds of plugin outputs.

Because `itemReplacementDirectories` returns a unique temporary directory on each call, I don't believe including it in the sandbox profile had the intended effect, so removing it should not break existing plugins.

### CODE REVIEW

**Comment by owenv** [comment]
@swift-ci please test

**Comment by owenv** [comment]
@swift-ci please test source compatibility

**Review by francescomikulis — APPROVED** [review]

**Comment by owenv** [comment]
@swift-ci please test package compatibility

**Comment by owenv** [comment]
Reworked this a bit so we still include item replacement directories which should remain stable

**Comment by owenv** [comment]
@swift-ci please test

**Comment by owenv** [comment]
@swift-ci please test package compatibility

**Review by dschaefer2 — APPROVED** [review]

**Comment by owenv** [comment]
@swift-ci please test Windows platform

**Comment by owenv** [comment]
@swift-ci please test package compatibility

**Pull request merged**
