### PR TITLE
Revert "Support separate modules for static and dynamic exporting symbols for Windows"

### PR DESCRIPTION
**Pull request by dschaefer2**
Reverts swiftlang/swift-package-manager#8049

We are seeing link errors and missing symbols. Reverting to investigate.

### CODE REVIEW

**Comment by dschaefer2** [comment]
@swift-ci please test

**Review by MaxDesiatov — APPROVED** [review]

**Review by jakepetroules — APPROVED** [review]

**Comment by dschaefer2** [comment]
@swift-ci please test macOS

**Comment by dschaefer2** [comment]
@swift-ci please test macOS self hosted

**Comment by dschaefer2** [comment]
@swift-ci please test macOS self hosted

**Comment by dschaefer2** [comment]
@swift-ci please test macOS self hosted

**Comment by hjyamauchi** [comment]
@swift-ci please test macOS self hosted

**Comment by hjyamauchi** [comment]
Hi @dschaefer2 I think that the above self-hosted macos CI is broken:

https://ci.swift.org/job/swift-package-manager-with-xcode-self-hosted-PR-osx/4531/
```   /private/var/folders/bb/hcrjxg1s0b96pfst0ymhmp240000gn/T/Miscellaneous_TestableAsyncExe.UINhTP/Miscellaneous_TestableAsyncExe/Sources/TestableAsyncExe4/NonMain.swift:3:22: error: concurrency is only available in macOS 10.15.0 or newer
     1 | @main
     2 | struct AsyncMain4 {
       |        `- note: add @available attribute to enclosing struct
     3 |   static func main() async {
       |               |      `- error: concurrency is only available in macOS 10.15.0 or newer
       |               `- note: add @available attribute to enclosing static method
     4 |     print(await getGreeting4())
     5 |   }
```

due to what appears to be an xcode/toolchain update on the CI runners:

Last passing run: https://ci.swift.org/job/swift-package-manager-with-xcode-self-hosted-PR-osx/4510/
```swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.51 clang-1500.1.0.2.2)```

Failing: https://ci.swift.org/job/swift-package-manager-with-xcode-self-hosted-PR-osx/4531/
```Apple Swift version 6.1-dev (LLVM 5c0d283c37132bf, Swift b5af518638c9a16)```

I cannot directly influence this. Can you look into this?

**Comment by dschaefer2** [comment]
@swift-ci please test macOS self hosted.

**Comment by dschaefer2** [comment]
Yes, we've been having issues with the MacOS self hosted job which we upgraded to use snapshot builds so we can start using swift-testing, but that was probably a bad idea, so we're working to revert it back to 6.0.2. Sorry about the delays.

**Comment by dschaefer2** [comment]
@swift-ci please test macOS self hosted

**Comment by dschaefer2** [comment]
OK, this is taking so long I ended up with a better solution. #8117 

Closing.

**Pull request closed without merging**
