### PR TITLE
NFC: Add `AsyncStream`-based API to `AsyncProcess`

### PR DESCRIPTION
**Pull request by MaxDesiatov**
Existing `AsyncProcess` closure-based API for `stdout` and `stderr` consumption requires a lot of tedious and error-prone ceremony for use of `async`. One needs to manually create `AsyncStream`s and their continuations, feed the output via the continuations, spawn a task group and consume the output in separate tasks, while launching the process at the same time.

We should provide a simpler `popen`-like API that allows passing `async` closures that receive ready for iteration `AsyncStream`s as arguments.

No functional change is made in this PR, the new API is not used yet outside of corresponding tests.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Review by AndrewHoos — APPROVED** [review]

**Comment by xedin** [comment]
@swift-ci please test

**Review by xedin — APPROVED** [review]

**Pull request merged**
