### PR TITLE
[DONT MERGE] Verify Swift CI workflows

### PR DESCRIPTION
**Pull request by shahmishal**
_[One line description of your change]_

### Motivation:

_[Explain here the context, and why you're making that change. What is the problem you're trying to solve.]_

### Modifications:

_[Describe the modifications you've done.]_

### Result:

_[After your change, what will change.]_

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci please test package compatibility

**Comment by shahmishal** [comment]
@swift-ci please smoke test self hosted

**Comment by shahmishal** [comment]
@swift-ci please test self hosted

**Comment by shahmishal** [comment]
@swift-ci please smoke test

**Comment by shahmishal** [comment]
@swift-ci please test

**Review by bkhouri — CHANGES_REQUESTED** [review]
Requesting change to ensure this PR does not get merged.

**Pull request closed without merging**
