### PR TITLE
Update swift-toolchain-sqlite

### PR DESCRIPTION
**Pull request by jakepetroules**
Adapt to rename RE swiftlang/swift-toolchain-sqlite#5

### CODE REVIEW

**Review by owenv — APPROVED** [review]

**Comment by jakepetroules** [comment]
https://github.com/swiftlang/swift-llbuild/pull/933
@swift-ci please test

**Comment by jakepetroules** [comment]
@swift-ci please test macOS

**Comment by jakepetroules** [comment]
https://github.com/swiftlang/swift-llbuild/pull/933
@swift-ci please test macOS Linux

**Comment by jakepetroules** [comment]
https://github.com/swiftlang/swift-llbuild/pull/933
@swift-ci please test Linux

**Comment by jakepetroules** [comment]
swiftlang/swift-llbuild#933
@swift-ci please test

**Comment by jakepetroules** [comment]
swiftlang/swift-llbuild#933
swiftlang/swift-toolchain-sqlite#/7
@swift-ci please test

**Comment by jakepetroules** [comment]
swiftlang/swift-llbuild#933
swiftlang/swift-toolchain-sqlite#7
@swift-ci please test

**Comment by jakepetroules** [comment]
swiftlang/swift-llbuild#933
swiftlang/swift-toolchain-sqlite#7
@swift-ci please smoke test Linux

**Comment by jakepetroules** [comment]
swiftlang/swift-llbuild#933
swiftlang/swift-toolchain-sqlite#7
@swift-ci please test Windows

**Comment by jakepetroules** [comment]
swiftlang/swift-llbuild#933
swiftlang/swift-toolchain-sqlite#7
@swift-ci please smoke test linux

**Comment by jakepetroules** [comment]
swiftlang/swift-llbuild#933
swiftlang/swift-toolchain-sqlite#7
@swift-ci smoke test linux

**Comment by jakepetroules** [comment]
swiftlang/swift-llbuild#933
swiftlang/swift-toolchain-sqlite#7
@swift-ci please test linux

**Pull request merged**
