### PR TITLE
Add tests for `Basics/AsyncProcess`

### PR DESCRIPTION
**Pull request by MaxDesiatov**
`AsyncProcess` replicates `TSCBasic.Process` with additions that make it easier to use with Swift Concurrency. To date we didn't replicate the test suite for it, this PR aims to fix that omission.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test linux

**Comment by MaxDesiatov** [comment]
@swift-ci test linux

**Comment by MaxDesiatov** [comment]
@swift-ci test linux

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Review by bnbarham — APPROVED** [review]

**Review by xedin — COMMENTED** [review]
This is great, thank you!

**Pull request merged**
