### PR TITLE
Mark all test classes fileprivate

### PR DESCRIPTION
**Pull request by jakepetroules**
This reduces the number of unnecessary exported symbols.

### CODE REVIEW

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Comment by jakepetroules** [comment]
Actually, this technique doesn't work with XCTest on Windows (only Swift Testing), never mind.

**Comment by dschaefer2** [comment]
The -static changes in the build manifest generator are working so far.

**Comment by jakepetroules** [comment]
I consider this best practice regardless. :)

**Pull request closed without merging**
