### PR TITLE
Log timestamps in the bootstrap scripts

### PR DESCRIPTION
**Pull request by MaxDesiatov**
### Motivation:

This enables detailed analysis of timings of different build phases of the bootstrap scripts.

### Modifications:

Log messages as produced by `Utilities/helpers.py` also output timestamps in the ISO format.

### Result:

It's easier to analyze build phases timing.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci test macos

**Comment by MaxDesiatov** [comment]
@swift-ci test macos

**Review by dschaefer2 — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Pull request merged**
