### PR TITLE
Convert more package collections code to `async`/`await`

### PR DESCRIPTION
**Pull request by AndrewHoos**
Async package collection provider

### Motivation:

Safer more readable code ready for Swift 6

### Modifications:

Moved PackageCollectionProvider to async/await

### Result:

Removed numerous completion handler methods

### CODE REVIEW

**Comment by AndrewHoos** [comment]
@swift-ci test

**Comment by AndrewHoos** [comment]
@swift-ci test

**Comment by AndrewHoos** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Review by MaxDesiatov — APPROVED** [review]

**Pull request merged**
