### PR TITLE
Remove usage of `temp_await` in PackageContainer

### PR DESCRIPTION
**Pull request by AndrewHoos**
Remove usage of `temp_await` in PackageContainer

### Motivation:

`temp_await` is unsafe and it would be better to use true async methods

### Modifications:

Remove `temp_await` from PackageContainer

### Result:

Safer more modern Swift code

### CODE REVIEW

**Comment by AndrewHoos** [comment]
@swift-ci test

**Comment by AndrewHoos** [comment]
@swift-ci test

**Comment by AndrewHoos** [comment]
@swift-ci test Linux

**Comment by AndrewHoos** [comment]
@swift-ci test

**Comment by AndrewHoos** [comment]
@swift-ci test Windows

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Review by MaxDesiatov — APPROVED** [review]

**Pull request merged**
