### PR TITLE
Handle the "abnormal-exit" status kind from the Swift compiler's parseable output

### PR DESCRIPTION
**Pull request by jakepetroules**
This is used on Windows.

### CODE REVIEW

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test linux

**Pull request merged**
